{% set name = "ml4xcube" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ml4xcube-{{ version }}.tar.gz
  sha256: 6a61432b4878f7ac45fe59ff3b5e8859f096e8c7b32d8be8d03b95cf88c446d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2023.2.0
    - dask >=2023.2.0
    - numpy >=1.24
    - pandas >=2.2
    - scikit-learn >1.3.1
    - xarray >2023.8.0
    - zarr >2.11
    - rechunker >=0.5.1


test:
  requires:
    - python {{ python_min }}
  imports:
    - ml4xcube
  # disabling pip check until an upstream issue with dask-image is resolved. See:
  # https://github.com/conda-forge/dask-image-feedstock/issues/25
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://pypi.org/project/ml4xcube/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ML package for data cubes'
  description: 'ML package for data cubes'
  doc_url: https://deepesdl.readthedocs.io/en/latest/ml-toolkit/introduction/
  dev_url: https://github.com/deepesdl/ML-Toolkits/tree/develop/mltools/ml4xcube

extra:
  recipe-maintainers:
    - Julia310
