{% set name = "ml4xcube" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml4xcube-{{ version }}.tar.gz
  sha256: 71940469581071621384ba9b9f6ff89e4494612595de4392c4f6932c8741fb3c
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask-core >=2023.2.0
    - dask >=2023.2.0
    - numpy >=1.24
    - pandas >=2.2
    - scikit-learn >1.3.1
    - xarray >2023.8.0
    - zarr >2.11
    - rechunker >=0.5.1

test:
  imports:
    - ml4xcube
  # disabling pip check until an upstream issue with dask-image is resolved. See:
  # https://github.com/conda-forge/dask-image-feedstock/issues/25
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://pypi.org/project/ml4xcube/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ML package for data cubes'
  description: 'ML package for data cubes'
  doc_url:  https://deepesdl.readthedocs.io/en/latest/ml-toolkit/introduction/
  dev_url:  https://github.com/deepesdl/ML-Toolkits/tree/develop/mltools/ml4xcube

extra:
  recipe-maintainers:
    - Julia310
